services:
  go-app:
    platform: linux/arm/v7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT:-18080}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway" # IMPORTANT Update the `localhost` usages in the config file to `host.docker.internal`